site_name: LITMUS
site_url: https://github.com/HughMcDougall/litmus/
site_author: Hugh McDougall

edit_uri: ""
repo_name: HughMcDougall/litmus/
repo_url: https://github.com/HughMcDougall/litmus/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - search.suggest
    - search.highlight
    - search.tabs.link
    - navigation.expand
    - toc.follow
    - navigation.tracking
    - toc.integrate
    - content.code.copy  # Adds a copy-to-clipboard button
    - content.code.annotate  # For annotated lines (optional)
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
extra_css: [custom.css]
plugins:
  mkdocstrings:
    handlers:
      python:
        paths: [.]
        import:
          - https://docs.python.org/3/objects.inv
          - https://docs.pydantic.dev/latest/objects.inv
        options:
          members_order: source
          group_by_category: true
          separate_signature: false
          show_inherited_members: true
          filters:
              - "!^_"               # Hide private members
          show_root_heading: false
          show_if_no_docstring: true
          show_signature_annotations: true
          signature_without_default: true
          show_source: true       # Do not show source code link
          show_signature: true     # Show function/method signatures
          show_root_full_path: false
          show_object_full_path: false
          indent: 4
          docstring_style: sphinx  # or "numpy", "restructuredtext"
          show_bases: true
          show_symbol_type_heading: true
          merge_init_into_class: true
          heading_level: 4
          show_code_examples: false  # Disable example blocks (if parsed)
          
          preserve_docstring_spacing: true
          use_docstring_inheritance: true
  search: {}

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Code Docs:
      - For Users:
          - models: models.md
          - fittingmethods: fitting_methods.md
          - litmusclass: litmusclass.md
          - lightcurve: lightcurve.md
          - mocks: mocks.md
      - For Developers:
          - lin_scatter: lin_scatter.md
          - GP_working: GP_working.md
          - logging: logging.md
          - Utilities and Typing: _utils.md
  - Examples & Tutorials:
      - Getting Started: gettingstarted.md
      - LITMUS vs Aliasing: examples/JAVELIN_HeScan_Comparison/JAVELIN_HeScan_Comparison.md
      - Constraining a Lightcurve: examples/lightcurve_gentest/lightcurve_gentest.md
      - Creating a Custom Statistical Model: examples/Custom_statsmodel_example/Custom_statsmodel_example.md
      - Using Litmus to Remove False Positives: examples/Model_comparison_example/Model_comparison_example.md
      