site_name: LITMUS
site_url: https://github.com/HughMcDougall/litmus/
site_author: Hugh McDougall

edit_uri: ""
repo_name: HughMcDougall/litmus/
repo_url: https://github.com/HughMcDougall/litmus/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - search.suggest
    - search.highlight
    - search.tabs.link
    - navigation.expand
    - toc.follow
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
extra_css: [custom.css]
plugins:
  autorefs: {}
  mkdocstrings:
    handlers:
      python:
        paths: [.]
        import:
          - https://docs.python.org/3/objects.inv
          - https://docs.pydantic.dev/latest/objects.inv
        options:
          members_order: source
          group_by_category: true
          separate_signature: false
          show_inherited_members: false
          filters:
              - "!^_"               # Hide private members
          show_root_heading: false
          show_if_no_docstring: false
          show_signature_annotations: true
          show_source: true       # Do not show source code link
          show_signature: true     # Show function/method signatures
          show_root_full_path: false
          show_object_full_path: false
          indent: 4
          docstring_style: sphinx  # or "numpy", "restructuredtext"
          show_bases: true
          show_symbol_type_heading: true
          merge_init_into_class: true
          heading_level: 4
          show_code_examples: false  # Disable example blocks (if parsed)
          
          preserve_docstring_spacing: true
          use_docstring_inheritance: true
  search: {}



nav:
  - Home: index.md
  - Code Docs:
      - fittingmethods: fitting_methods.md
      - lightcurve: lightcurve.md
      - litmusclass: litmusclass.md
      - logging: logging.md
      - mocks: mocks.md
      - models: models.md
      - lin_scatter: lin_scatter.md
      - GP_working: GP_working.md
      - utilities: _utils.md
  - Examples:
      - Home: index.md