[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "LITMUS"
version = "0.1.0"
authors = [
  { name="Hugh McDougall", email="hughmcdougallemail@gmail.com" },
]
dependencies = [
  'jax',
  'jaxlib',
  'jaxopt',
  'numpyro',
  'tinygp',
  'matplotlib',
  'numpy',
  'etils',
  'tensorflow_probability',
  'jaxns==2.0.1',
  'chainconsumer==0.34.0',
  'scipy'
]

description = "JAX-based lag recovery for AGN reverberation mapping"
readme = "README.md"
requires-python = ">=3.7"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
homepage = "https://github.com/HughMcDougall/LITMUS"

[tool.setuptools.packages.find]
where = ["."]  # list of folders that contain the packages (["."] by default)
include = ["./litmus"]  # package names should match these glob patterns (["*"] by default)
exclude = []  # exclude packages matching these glob patterns (empty by default)
namespaces = false  # to disable scanning PEP 420 namespaces (true by default)